### ISSUE TITLE
`Show Speaking Users Only` option not working

### ISSUE THREAD

**Issue by Ganbin** [Naozumi520/discordOverlayMac#1]
When I check the `Show Speaking Users Only` it is not working.

According to : [https://www.reddit.com/r/Twitch/comments/qzr65z/discord_streamkit_only_speakers_toggle_not_working/](Discord Streamkit (Only Speakers toggle not working))

```
I've been having the same problem and I just found the solution, it's so dumb. Apparently parts of the code are now case sensitive.
Find the part of your browser source link that says "limit_speaking=true" and change it to say "limit_speaking=True".
Fixed it for me.
```

I have tried in OBS and it also work when I set to `True` instead of `true`.

I am now trying to get your code on my computer to see if I can do something.

I also think that all other value that are `true` instead of `True` are also buggy.

**Comment by Ganbin** [comment]
I have made a pull request to fix the issue. On my side it works with the change.

**Comment by Naozumi520** [comment]
Ah, I've been using the default values only so I didn't notice, thanks! it was a big help.
I've merged the pull request and I will publish the app after packaging.

**Comment by Naozumi520** [comment]
I released an [update](https://github.com/Naozumi520/discordOverlayMac/releases/tag/1.0.3) from the pull request. Thanks again! ❤️

**Comment by Ganbin** [comment]
Thank you so much. ❤️
